// Run lifecycle. Authoritative raw snapshots stay private to this closure.
(function(){'use strict';
let raw=null, humans=[], generation=0, timer=null, socket=null;
const state={id:null,status:null,headHash:null,version:0,tick:0,modified:false,events:[],selected:null,error:null,mode:'observer'};
function notify(){if(window.Run.onChange)window.Run.onChange();}
async function request(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d;try{d=await r.json();}catch(_){d={};}if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||d));return d;}
function accept(d){if(raw&&d.state&&d.state.state_version<state.version)return;raw=d.state||null;state.status=d.status;state.headHash=d.head_hash;state.version=raw?.state_version||0;state.tick=raw?.simulated_time||0;state.mode=raw?.world_facts?.interaction_mode||raw?.mode||d.metadata?.mode||'observer';state.modified=!!(raw?.world_facts?.creative_modified||d.metadata?.modified||raw?.modified||raw?.interventions?.length);}
async function refresh(){const g=generation,id=state.id;if(!id)return;try{const d=await request('/runs/'+encodeURIComponent(id));if(g!==generation)return;accept(d);state.error=null;humans=Object.values(raw?.humans||{});notify();}catch(e){if(g===generation){state.error=e.message;notify();}}}
async function fetchEvents(){const g=generation,id=state.id;if(!id)return;try{const d=await request('/runs/'+encodeURIComponent(id)+'/events?after='+String(state.events.at(-1)?.event_index??Math.max(-1,state.version-61)));if(g!==generation)return;mergeEvents(Array.isArray(d)?d:d.events||[]);notify();}catch(e){if(g===generation){state.error=e.message;notify();}}}
function mergeEvents(incoming){const seen=new Map(state.events.map(e=>[e.event_index,e]));for(const e of incoming)seen.set(e.event_index,e);state.events=Array.from(seen.values()).sort((a,b)=>a.event_index-b.event_index).slice(-60);}
function stop(){generation++;clearInterval(timer);timer=null;if(socket){socket.onclose=null;socket.close();socket=null;}raw=null;humans=[];Object.assign(state,{id:null,status:null,headHash:null,version:0,tick:0,modified:false,events:[],selected:null,error:null,mode:'observer'});notify();}
async function loadRun(id){stop();state.id=id;const url=new URL(location.href);if(id)url.searchParams.set('world',id);else url.searchParams.delete('world');history.replaceState(null,'',url);if(!id)return;const g=generation;await refresh();await fetchEvents();if(g!==generation)return;timer=setInterval(()=>{if(socket?.readyState!==WebSocket.OPEN){refresh();fetchEvents();}},2500);try{socket=new WebSocket((location.protocol==='https:'?'wss':'ws')+'://'+location.host+'/ws/'+encodeURIComponent(id)+'?after='+String(state.events.at(-1)?.event_index??-1));socket.onmessage=message=>{if(g!==generation)return;try{const d=JSON.parse(message.data);if(d.type==='error')throw Error(d.detail);if(d.state){accept(d);humans=Object.values(raw.humans||{});mergeEvents(d.events||[]);notify();}}catch(e){state.error=e.message;notify();}};}catch(_){}}
async function command(action,body={}){if(!state.id)return;try{const d=await request('/runs/'+encodeURIComponent(state.id)+'/'+action,body);await refresh();await fetchEvents();return d;}catch(e){state.error=e.message;notify();throw e;}}
function publicHumans(){return humans.map(h=>({id:h.human_id||h.id,name:h.name,map_id:h.map_id,x:h.x,y:h.y,facing:h.facing,role:h.role,badges:h.badges||[],activity:h.activity,active_plan:h.active_plan?{kind:h.active_plan.kind,destination_map:h.active_plan.destination_map}:null,battle_id:h.battle_id,service_request:!!h.service_request,status:h.status,appearance:h.appearance}));}
window.Run={get state(){return {...state,events:state.events.slice()};},loadRun,refresh,fetchEvents,stop,request,command,pause:()=>command('pause'),resume:()=>command('resume'),selectHuman(id){state.selected=id;notify();},publicHumans,inspectPokemon(id){const p=raw?.pokemon?.[id];return p?JSON.parse(JSON.stringify(p)):null;},observerSnapshot(){if(!raw)return null;const battles={};for(const [id,b] of Object.entries(raw.world_facts?.battles||{})){const session=b.session||{};battles[id]={session:{teams:session.teams,result:{pokemon:session.result?.pokemon,observations:session.result?.observations}}};}return JSON.parse(JSON.stringify({world_facts:{battles,static_encounters:Object.fromEntries(Object.entries(raw.world_facts?.static_encounters||{}).map(([id,claim])=>[id,{status:claim.status,pokemon_id:claim.pokemon_id}]))}}));},inspectHuman(id){const h=humans.find(x=>(x.human_id||x.id)===id);return h?JSON.parse(JSON.stringify(h)):null;},onChange:null};
})();
