import {createHistoryPager} from '/client/unified/history-pager.mjs';
import {eventText} from '/client/live/model.mjs';
import {inventoryPockets,itemName,pcBoxes,tradeRows,setItemMetadata} from '/client/unified/entity-inventory.mjs';
import {mountInferenceView} from '/client/unified/inference-view.mjs';
const $=id=>document.getElementById(id),q=new URLSearchParams(location.search);let world=q.get('world'),person=q.get('human_id'),state=null,events=[],requestVersion=0,historyRequestVersion=0,searchTimer=null;
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
const readable=value=>typeof value==='string'?value.replaceAll('_',' '):JSON.stringify(value,null,2);
async function get(url){const r=await fetch(url);if(!r.ok)throw Error('Could not load saved world ('+r.status+').');return r.json();}
function section(title,value){const box=el('section');box.append(el('h2',title),el('pre',readable(value??'None recorded')));$('profile').append(box);}
function profileSection(title){const box=el('section');box.append(el('h2',title));$('profile').append(box);return box;}
function renderContinuity(h){
 const life=h.individual_life||{},task=life.task,box=profileSection('Purpose & next step');
 box.append(el('p',life.aspiration?.text||h.goal?.text||'No aspiration recorded.'));
 if(life.commitment?.text)box.append(el('p','Commitment: '+life.commitment.text));
 if(!task){box.append(el('p','No concrete next step chosen yet.'));return;}
 const labels={planned:'Planned',executing:'In progress',paused:'Paused',blocked:'Blocked',completed:'Completed',abandoned:'Abandoned'};
 box.append(el('h3',(labels[task.execution_state||task.status]||task.status)+' · '+task.purpose));
 const expected=task.expected_result||{},place=expected.map_id?.replaceAll('_',' ');
 const resultLabel={location:'Reach '+place+(expected.x!==undefined?' at ('+expected.x+', '+expected.y+')':''),party_acquisition:'Add a Pokémon to the party',service:'Complete the requested service',activity:'Finish the '+expected.activity_kind+' activity',battle_resolution:'Finish the training battle'};
 if(resultLabel[expected.kind])box.append(el('p','Expected result: '+resultLabel[expected.kind]));
 if(task.blocked_reason)box.append(el('p',task.blocked_reason));
 if(task.last_transition?.reason)box.append(el('p','Latest choice: '+task.last_transition.reason));
 if(task.result)box.append(el('p','The expected step result was recorded in the world history.'));
 box.append(el('small','Completing a step does not automatically complete the whole commitment.'));
 if(life.task_history?.length){const previous=el('details');previous.append(el('summary','Previous steps · '+life.task_history.length));for(const old of life.task_history)previous.append(el('p',(labels[old.status]||old.status)+' · '+old.purpose));box.append(previous);}
}
function pocketList(target,inventory,showEmpty=false){const groups=inventoryPockets(inventory);for(const pocket of groups){if(!showEmpty&&!pocket.items.length)continue;const card=el('div');card.className='card';card.append(el('h3',pocket.name));const list=el('ul');list.className='item-list';for(const item of pocket.items){const row=el('li');row.append(el('span',item.name),el('strong','× '+item.quantity));list.append(row);}if(!pocket.items.length)card.append(el('small','Empty'));else card.append(list);target.append(card);}return groups.reduce((count,pocket)=>count+pocket.items.length,0);}
function mailCard(letter,label='Letter'){const card=el('details');card.className='card';card.append(el('summary',label+' · '+itemName(letter.item||'mail')+' · From '+(letter.author_name||state.humans?.[letter.author_id]?.name||letter.author_id||'Unknown author')));card.append(el('p',letter.text||'No message recorded'),el('small','Written with '+(letter.species?.replaceAll('_',' ')||'Unknown Pokémon')+' · '+(letter.mail_id||'No letter identifier')));return card;}
function renderInventory(h){const bag=profileSection('Bag & items');bag.append(el('small','Observer view · inventories and trades are managed by the people in the world.'));bag.append(el('p','Registered item: '+(h.registered_item?itemName(h.registered_item):'None')));const grid=el('div');grid.className='grid';pocketList(grid,h.inventory,true);bag.append(grid);const pc=profileSection('PC item storage');const pcGrid=el('div');pcGrid.className='grid';if(!pocketList(pcGrid,h.pc_items))pc.append(el('p','No items deposited.'));pc.append(pcGrid);const mailbox=profileSection('PC mailbox · '+Object.keys(h.mailbox||{}).length+' / 10');if(!Object.keys(h.mailbox||{}).length)mailbox.append(el('p','No letters deposited.'));for(const letter of Object.values(h.mailbox||{}))mailbox.append(mailCard(letter));}
function pokemonCard(id,label){const p=state.pokemon?.[id],card=el('details');card.className='card pokemon-card';if(!p){card.append(el('summary',label+' · '+id),el('p','Individual details are unavailable in this snapshot.'));return card;}const title=p.nickname||p.species?.replaceAll('_',' ')||id;card.append(el('summary',label+' · '+title+' · Lv '+(p.level??'?')));card.append(el('p','HP '+(p.hp??'?')+'/'+(p.stats?.hp??'?')+' · '+(p.status||'Healthy')));card.append(el('p','Held item: '+(p.held_item?itemName(p.held_item):'None')));if(p.mail)card.append(mailCard(p.mail,'Attached letter'));const moves=(p.moves||[]).map(move=>typeof move==='string'?move.replaceAll('_',' '):(move.move||move.name||move.move_id||'?').replaceAll('_',' ')+' (PP '+(move.pp??'?')+')');card.append(el('p','Moves: '+(moves.join(', ')||'None recorded')));const record=el('details');record.append(el('summary','Individual record & ownership history'),el('pre',readable(p)));card.append(record);return card;}
function renderPokemon(h){const party=profileSection('Pokémon party · '+(h.party?.length||0)+' / 6');const grid=el('div');grid.className='grid';for(let slot=0;slot<6;slot++){const id=h.party?.[slot];if(id)grid.append(pokemonCard(id,'Slot '+(slot+1)));else{const empty=el('div','Slot '+(slot+1)+' · Empty');empty.className='empty-slot';grid.append(empty);}}party.append(grid);const storage=profileSection('Pokémon PC · '+new Set(h.box||[]).size+' stored');const {boxes,overflow,currentBox}=pcBoxes(h);storage.append(el('p','14 boxes · 30 slots each · Current box: '+(boxes[currentBox-1].name)));if(!h.pc_storage)storage.append(el('small','Existing stored Pokémon are shown in sequential slots.'));for(const box of boxes){const panel=el('details');panel.className='pc-box';panel.open=box.number===currentBox;panel.append(el('summary',box.name+' · '+box.slots.filter(Boolean).length+' / 30'+(box.number===currentBox?' · Current':'')));const slots=el('div');slots.className='grid';for(const [slot,id] of box.slots.entries()){if(id)slots.append(pokemonCard(id,'Slot '+(slot+1)));else{const empty=el('div','Slot '+(slot+1)+' · Empty');empty.className='empty-slot';slots.append(empty);}}panel.append(slots);storage.append(panel);}if(overflow.length){storage.append(el('p','Stored individuals without an available box slot:'));for(const id of overflow)storage.append(pokemonCard(id,'Unassigned'));}const placed=new Set([...(h.party||[]),...(h.box||[])]);const unassigned=Object.entries(state.pokemon||{}).filter(([id,p])=>p.owner_id===person&&!placed.has(id));if(unassigned.length){const section=profileSection('Other owned Pokémon · placement not recorded');for(const [id] of unassigned)section.append(pokemonCard(id,'Unassigned'));}}
function renderTrades(){const section=profileSection('Trades between people');const rows=tradeRows(state,person);section.append(el('small','Offers require the people’s decisions. Completed trades and their full event history remain recorded below.'));if(!rows.length)section.append(el('p','No trade offers recorded.'));for(const trade of rows){const card=el('article');card.append(el('strong',trade.kind+' trade with '+trade.partner),el('p',trade.status));const terms=el('div');terms.className='grid';const giving=el('div'),receiving=el('div');giving.append(el('small',trade.active?'Offers':'Offered'),el('p',trade.giving));receiving.append(el('small',trade.active?'Requests':'Requested'),el('p',trade.receiving));terms.append(giving,receiving);card.append(terms,el('small',trade.id+' · Recorded version '+trade.version));section.append(card);}}
function renderProfile(){const npc=state?.npcs?.[person];if(npc){$('profile').replaceChildren();$('name').textContent=npc.name||'Local resident';const card=profileSection('Original Kanto resident');card.append(el('p',npc.map_id.replaceAll('_',' / ').replace(/([a-z])([A-Z])/g,'$1 $2')),el('p','An original game resident, staying near their familiar location.'));if(npc.dialogue){const speech=profileSection('Game dialogue');for(const text of npc.dialogue.text.split('\n\n'))speech.append(el('p',text));}const reference=el('details');reference.append(el('summary','Original game reference'),el('pre',readable(npc.source)));$('profile').append(reference);return;}const h=state?.humans?.[person];$('profile').replaceChildren();if(!h){$('name').textContent='Choose a person';return;}$('name').textContent=h.name;section('Life & current status',{biography:h.biography,role:h.role,location:h.map_id,position:{x:h.x,y:h.y},money:h.money,goal:h.goal,individual_life:h.individual_life,status:h.status,personality:h.personality,interests:h.interests});renderContinuity(h);if(h.cognition?.latest){const thought=h.cognition.latest;section('Thoughts & ongoing actions',{current_movement:h.movement_intent?{action:h.movement_intent.action,destination:h.movement_intent.arguments}:null,current_activity:h.activity?.kind,latest_thought:thought.text,thought_kind:thought.kind,proposed_next_action:thought.proposed_action,proposed_arguments:thought.proposed_arguments,meaning:'A thought or suggestion; actions and completed results are recorded separately.'});}mountInferenceView($('profile'),{world,person});if(h.workplace){const staff=Object.values(state.humans||{}).filter(o=>['service_staff','shop_staff'].includes(o.role)&&o.service_assignment?.map_id===h.workplace.map_id&&o.service_assignment?.kind===h.workplace.kind&&o.map_id===h.workplace.map_id&&!o.battle_id&&!o.service_request&&!o.activity&&!o.movement_intent&&(o.ready_at||0)<=(state.simulated_time||0)&&(!o.workplace?.service_post||o.x===o.workplace.service_post.x&&o.y===o.workplace.service_post.y));section('Home & workplace',{home_base:h.home_location?.map_id,workplace:h.workplace.map_id,at_workplace:h.map_id===h.workplace.map_id,service_post:h.workplace.service_post,at_service_post:!h.workplace.service_post||h.map_id===h.workplace.map_id&&h.x===h.workplace.service_post.x&&h.y===h.workplace.service_post.y,on_duty:h.service_assignment?(h.map_id!==h.workplace.map_id||!staff.some(o=>o.human_id!==h.human_id)):(state.simulated_time||0)%43200<28800,...(h.service_assignment?{covering_staff:staff.filter(o=>o.human_id!==h.human_id).map(o=>o.name),service_available:staff.length>0}:{})});}section('Badges & achievements',{badges:h.badges||[],achievements:h.achievements,progression:h.progression,acquisition:h.acquisition});renderInventory(h);renderPokemon(h);renderTrades();
section('Relationships · their assessments',Object.fromEntries(Object.entries(h.relationships||{}).map(([id,v])=>[state.humans[id]?.name||id,v])));section('Memories · their own account',h.memories||[]);const raw=el('details');raw.append(el('summary','All recorded person data'),el('pre',readable(h)));$('profile').append(raw);}
function renderHistory(){const rows=events;$('count').textContent=rows.length+' matching events loaded · newest first'+(historyPager.hasMore?' · older history available':'');$('history').replaceChildren();for(const e of rows){const row=el('article');row.append(el('strong',eventText(e,state.humans)),el('p','#'+e.event_index+' · '+Math.floor((e.simulated_time||0)/60)+' world minutes · '+e.event_kind));for(const decision of e.causation?.decisions||[e.causation]){const text=decision?.action_arguments?.text;if(text)row.append(el('p',(state.humans[decision.human_id]?.name||'Recorded speech')+': “'+text+'”'));}const details=el('details');details.append(el('summary','Full event record'),el('pre',readable(e)));row.append(details);$('history').append(row);}$('more').hidden=!historyPager.hasMore;$('more').disabled=historyPager.loading;}
const historyPager=createHistoryPager(get);
let catalogPromise;
async function loadHistory(reset=true){
 if(!state||!world||!person||(!reset&&historyPager.loading))return;
 const token=++historyRequestVersion;$('notice').textContent='Loading matching saved history…';
 try{
  const request=reset?historyPager.reset({world,person,throughVersion:state.state_version,search:$('search').value,category:$('filter').value}):historyPager.next();
  events=historyPager.events;renderHistory();
  if(await request&&token===historyRequestVersion){events=historyPager.events;renderHistory();$('notice').textContent='Saved history through state version '+state.state_version+'. Load older pages below, or refresh for new activity.';}
 }catch(error){if(token===historyRequestVersion){$('notice').textContent=error.message;renderHistory();}}
}
async function load(){const version=++requestVersion;++historyRequestVersion;historyPager.invalidate();events=[];$('notice').textContent='Loading saved person…';try{catalogPromise??=get('/content/items.json').then(setItemMetadata).catch(()=>{});await catalogPromise;const snapshot=await get('/runs/'+encodeURIComponent(world));if(version!==requestVersion)return;state=snapshot.state;renderProfile();await loadHistory();}catch(e){if(version===requestVersion)$('notice').textContent=e.message;}}
for(const id of ['search','filter'])$(id).oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadHistory(),150);};$('more').onclick=()=>loadHistory(false);$('refresh').onclick=load;
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='kanto:selection'||typeof e.data.human_id!=='string')return;if(person!==e.data.human_id){person=e.data.human_id;clearTimeout(searchTimer);++requestVersion;if(state){renderProfile();loadHistory();}else load();}});load();
