import test from 'node:test';
import assert from 'node:assert/strict';
import {pcBoxes,inventoryPockets,tradeRows,setItemMetadata,itemName} from '../entity-inventory.mjs';
test('legacy storage gets sequential slots across 14 boxes without mutating saved data',()=>{const human={party:['party'],box:Array.from({length:32},(_,i)=>'p'+i)};const before=JSON.stringify(human),result=pcBoxes(human);assert.equal(result.boxes.length,14);assert.equal(result.boxes[0].slots.length,30);assert.equal(result.boxes[1].slots[1],'p31');assert.equal(JSON.stringify(human),before);});
test('explicit placements survive gaps; duplicate and invalid placements get distinct fallback slots',()=>{const human={party:['p0'],box:['p0','a','b','c','d','a'],pc_storage:{names:{14:'Favorites'},current_box:14,placements:{a:{box:14,slot:30},b:{box:14,slot:30},c:{box:0,slot:1}}}};const result=pcBoxes(human);assert.equal(result.currentBox,14);assert.equal(result.boxes[13].name,'Favorites');assert.equal(result.boxes[13].slots[29],'a');assert.deepEqual(result.boxes[0].slots.slice(0,3),['b','c','d']);assert.equal(result.boxes.flatMap(box=>box.slots).filter(Boolean).length,4);});
test('overflow individuals remain visible instead of being dropped',()=>{const result=pcBoxes({box:Array.from({length:422},(_,i)=>'p'+i)});assert.deepEqual(result.overflow,['p420','p421']);});
test('canonical bag pockets support aliases, structured quantities and unfamiliar saved items',()=>{const groups=inventoryPockets({ITEM_POKE_BALL:4,POTION:{quantity:2},HM01_CUT:1,ORAN_BERRY:3,BICYCLE:1,unknown_keepsake:1,ZERO:0,NEGATIVE:-2,FRACTION:1.5});assert.equal(groups.find(g=>g.key==='POKE_BALLS').items[0].quantity,4);assert.equal(groups.find(g=>g.key==='ITEMS').items[0].name,'Potion');assert.equal(groups.find(g=>g.key==='TM_HM').items[0].quantity,1);assert.equal(groups.find(g=>g.key==='KEY_ITEMS').items[0].quantity,1);assert.deepEqual(groups.find(g=>g.key==='OTHER').items.map(i=>i.name),['Unknown Keepsake']);});
test('trade direction, payment, phases and partner filtering match the inspected person',()=>{const state={humans:{a:{name:'Alice'},b:{name:'Bob'}},world_facts:{trade_offers:{item:{kind:'items',proposer:'a',recipient:'b',giving:{POTION:2},requesting:{POKE_BALL:1},payment:50,phase:'offered',offer_version:8},poke:{proposer:'b',recipient:'a',offered_pokemon:'p',wanted_species:'ABRA',counter_pokemon:'q',phase:'completed',completed_version:9},expired:{proposer:'a',recipient:'b',kind:'items',phase:'expired'},other:{proposer:'c',recipient:'d',phase:'offered'}}},pokemon:{p:{species:'MACHOP',level:10},q:{species:'ABRA',level:8}}};const before=JSON.stringify(state);const incoming=tradeRows(state,'b');assert.equal(incoming.length,3);assert.equal(incoming[0].partner,'Alice');assert.equal(incoming[0].giving,'Poké Ball × 1 · ₽50');assert.equal(incoming[0].receiving,'Potion × 2');assert.equal(incoming[1].status,'Completed');assert.match(incoming[1].giving,/MACHOP/);assert.equal(tradeRows(state,'a')[0].receiving,'Poké Ball × 1 · ₽50');assert.equal(incoming[2].status,'Expired');assert.equal(JSON.stringify(state),before);});
test('optional content metadata updates names without losing reference fallback',()=>{setItemMetadata({items:{SPECIAL_TEST:{name:'TEST KEEPSAKE',pocket:'POCKET_KEY_ITEMS'}}});assert.equal(itemName('special_test'),'Test Keepsake');assert.equal(inventoryPockets({SPECIAL_TEST:1}).find(g=>g.key==='KEY_ITEMS').items[0].name,'Test Keepsake');assert.equal(itemName('potion'),'Potion');});
